const actionType = {
  GET_BOOKS: 'GET_BOOKS',
  GET_BOOKS_PENDING: 'GET_BOOKS_PENDING',
  GET_BOOKS_REJECTED: 'GET_BOOKS_REJECTED',
  GET_BOOKS_FULFILLED: 'GET_BOOKS_FULFILLED',

  ADD_BOOK: 'ADD_BOOK',
  ADD_BOOK_PENDING: 'ADD_BOOK_PENDING',
  ADD_BOOK_REJECTED: 'ADD_BOOK_REJECTED',
  ADD_BOOK_FULFILLED: 'ADD_BOOK_FULFILLED',

  PATCH_BOOK: 'PATCH_BOOK',
  PATCH_BOOK_PENDING: 'PATCH_BOOK_PENDING',
  PATCH_BOOK_REJECTED: 'PATCH_BOOK_REJECTED',
  PATCH_BOOK_FULFILLED: 'PATCH_BOOK_FULFILLED',

  DELETE_BOOK: 'DELETE_BOOK',
  DELETE_BOOK_PENDING: 'DELETE_BOOK_PENDING',
  DELETE_BOOK_REJECTED: 'DELETE_BOOK_REJECTED',
  DELETE_BOOK_FULFILLED: 'DELETE_BOOK_FULFILLED',

  GET_TRENDING_BOOKS: 'GET_TRENDING_BOOKS',
  GET_TRENDING_BOOKS_PENDING: 'GET_TRENDING_BOOKS_PENDING',
  GET_TRENDING_BOOKS_REJECTED: 'GET_TRENDING_BOOKS_REJECTED',
  GET_TRENDING_BOOKS_FULFILLED: 'GET_TRENDING_BOOKS_FULFILLED',

  GET_NEW_BOOKS: 'GET_NEW_BOOKS',
  GET_NEW_BOOKS_PENDING: 'GET_NEW_BOOKS_PENDING',
  GET_NEW_BOOKS_REJECTED: 'GET_NEW_BOOKS_REJECTED',
  GET_NEW_BOOKS_FULFILLED: 'GET_NEW_BOOKS_FULFILLED',
}

export default actionType;